language: generic
dist: focal

script: 
 - sudo apt-get update
 - sudo apt-get install default-jre default-jdk nim g++ python3 -y
 - g++ pi_test_cpp.cpp
 - ./a.out
 - g++ pi_test_c.c
 - ./a.out
 - javac pi_test_java.java
 - java pi_test_java
 - sudo rm -rf pi_test_java.class
 - nim cpp -d:danger pi_test_nim.nim
 - ./pi_test_nim
 - python3 pi_test_python.py
